"""create logs table

Revision ID: 8292093dfc41
Revises: 
Create Date: 2025-03-31 21:25:11.150161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8292093dfc41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=False),
    sa.Column('request_uri', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details_matches', sa.Text(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_attack_type'), ['attack_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_logs_attack_type'))

    op.drop_table('logs')
    # ### end Alembic commands ###
